Rewrite the library to improve safety and prevent extra allocations.
This is a (major) rewrite of the library to avoid extra complexity, avoid
overriding symbols, and a bunch of other stuff.

That being said, I'm still not completely sure that this would fit well enough
for Servo, since the whole point of having it inside Servo is having access to
the metadata before loading all the video, and I haven't seen any tests
regarding this. I'll write one now, though.

I've verified that no leaks happen on the happy paths and some (most?) error
paths, and tried to reduce the logic to handle errors to a point where is
reviewable easily, but of course it's C so it needs careful review anyway.

Some of the problems with the previous implementation were:

 * Too generic symbols (could conflict easily).
 * Various leaks in error paths (IIRC).
 * Hackish ways to get durations, reporting invalid ones.
 * Lazy non-thread-safe initialization.
 * Didn't work with newer versions of LibAV*.

The API can of course be improved vastly, and multiple error messages can be
obtained via av_strerror and such.

```
ffi/info.c: In function ‘iterate_over_streams’:
ffi/info.c:72:9: warning: implicit declaration of function ‘avcodec_parameters_to_context’ [-Wimplicit-function-declaration]
     if (avcodec_parameters_to_context(avctx, ic->streams[i]->codecpar) < 0) {
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ffi/info.c:72:60: error: ‘AVStream {aka struct AVStream}’ has no member named ‘codecpar’; did you mean ‘codec’?
     if (avcodec_parameters_to_context(avctx, ic->streams[i]->codecpar) < 0) {
```